### ISSUE TITLE
App crash on Galaxy s8 devices 

### ISSUE THREAD

**Issue by asafazar92** [georg-jung/technion-robotic-arm#15]
When i open the app on my device, the app immediately crash without showing any screen ( when the bluetooth is turned on).
if the bluetooth is off, the connect screen shows, and after enabling it, the app crash.

**Comment by georg-jung** [comment]
Note the corresponding stack trace (taken from [Firebase](https://console.firebase.google.com/)):

    Fatal Exception: java.lang.IllegalArgumentException: scanner already started with given callback
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.startScanInternal(BluetoothLeScannerImplLollipop.java:21)
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.startScan(BluetoothLeScannerCompat.java:16)
        at com.gjung.haifa3d.viewmodel.ScannerViewModel.startScan(ScannerViewModel.java:16)
        at com.gjung.haifa3d.ScannerActivity.startScan(ScannerActivity.java:16)
        at com.gjung.haifa3d.ScannerActivity.access$startScan(ScannerActivity.java:16)
        at com.gjung.haifa3d.ScannerActivity$onCreate$1.onChanged(ScannerActivity.java:16)
        at com.gjung.haifa3d.ScannerActivity$onCreate$1.onChanged(ScannerActivity.java:16)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:29)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:44)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:14)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:18)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

That points us to [ScannerViewModel.java#L157](https://github.com/Haifa3D/haifa3d-hand-app/blob/9645b7011c0705ad1124bcabd9968752ea28537e/src/android/Haifa3d/app/src/main/java/com/gjung/haifa3d/viewmodel/ScannerViewModel.java#L157)

Seems like scanning is somehow started twice on your device, which leads to the crash. Feel free to drop a note if I should do anything more on this.

**Comment by mikimn** [comment]
Since @asafazar92 is assigned, he probably will deal with this bugfix on his own. Thanks @georg-jung for your input.

**Comment by asafazar92** [comment]
update: the app version on develop branch doesn't crash. it seems to be that only the app version on android app store crash on my device. so we will need to monitor this issue on the next release version.
